version: '3.8'

services:
  nextjs-pkm:
    build:
      context: .
    command: 'npm run dev -- -p 3000'
    container_name: nextjs-pkm
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
