version: '3.8'

services:
  nextjs-pkm:
    build:
      context: .
    command: 'npm run dev -- -p 3000'
    container_name: nextjs-pkm
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  pkm-next-postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE}'
    volumes:
      - 'pkm-next-pgsql:/var/lib/postgresql/data'

volumes:
  pkm-next-pgsql:
    driver: local
